apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "publish.fullname" . }}
  labels: {{- include "publish.labels" . | nindent 4 }}
data:
  default.conf: {{ .Values.config | toYaml | indent 4 }}
