apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "publish.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "publish.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "publish.labels" . | nindent 8 }}
    spec:
      {{- with .Values.defaults.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
          - name: data
            mountPath: /usr/share/nginx/html
            readOnly: true
      
      volumes:
      - name: config
        configMap:
          name: {{ include "publish.fullname" . }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "publish.fullname" . }}
