apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "publish.fullname" . }}
  labels: {{- include "publish.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
